### ISSUE TITLE
Need Comments and Notes For Recursion Problems

### ISSUE THREAD

**Issue by Shekhar389** [Shekhar389/Learning-DSA#1]

**Comment by anushkabishnoi** [comment]
Hello, this is my first experience with open source contributions. Would really appreciate it if you explained exactly what is needed to be done.

I would love to work on this issue.

Thanks in advance! :)

**Comment by Shekhar389** [comment]
@anushkabishnoi  I am glad to know you want to work on this.
Even I am new to open source and will love to work and collaborate with you in future to learn a lot.

Coming to work 
In this Repository Currently i had solved some standard DSA problembs in C++  and I want comments( Indiactating important logic of solution ) in the recursion problem solution.

So if you want to work on this Please let me know
